### ISSUE TITLE
New Flow Step to Get / Take Photo

### ISSUE THREAD

**Issue by fyhao** [fyhao/tns-webform-client#144]
New flow step to get / take photo, with ability to get the file blob, save to dropbox, or save to external URL.

Tasks:
------
- [x] New action take photo
- [x] Fix Bug in this issue https://github.com/fyhao/tns-webform-client/issues/201
- [x] Real device to test take photo without error
- [x] Simulator test image display in new single page which can back
- [x] Display test image in real device as above
- [x] Develop new blobVars to hold photo
- [x] http file upload photo
- [x] Real device test confirm http file upload ok

Additional Tasks:
------
- [x] New action displayImage #219  (Will open new single page accept image blob and display image)
- [x] Inject image into sharer action #220 
- [x] New action uploadFile #222

**Comment by fyhao** [comment]
![image](https://user-images.githubusercontent.com/1223477/27986986-9fa055d4-6439-11e7-8256-3b3e29297eb3.png)

nativeScript-camera got bugs

**Comment by fyhao** [comment]
Done Simulator test image display in new single page which can back

**Comment by fyhao** [comment]
Tested real device, second time, for first reinstallation, the first camera will crash, but subsequently will success.

OK, tested real device take picture and display image

**Comment by fyhao** [comment]
http file upload photo done

**Comment by fyhao** [comment]
Real device tested, the code passed through but nothing happened, server side did not detect request come in

**Comment by fyhao** [comment]
Tested again on sim and real device, confirm real device http file upload working now
