### ISSUE TITLE
Recategorize FlowEngine's steps into seperate step files module

### ISSUE THREAD

**Issue by fyhao** [fyhao/tns-webform-client#46]
Recategorize FlowEngine's steps into seperate step files module by studying electron-wf projects.

Steps Progress:
------
- [x] setValue
- [x] getValue
- [x] addValue
- [x] setHtml
- [x] addHtml
- [x] alert
- [x] openWebView
- [x] wait
- [x] requestFlow
- [x] setVar
- [x] evaljs
- [x] closewin
- [x] if

High level tasks
------
- [x] Created step modules
- [x] Make FlowEngine change to call step modules
- [x] Test FlowEngine modules

Additional Tasks
------
- [x] Move replaceAll into util refer #83
- [x] Move webform related into modWebform from modBrowser refer #84 
- [x] Modularize UI widget into seperate file refer #82 
- [x] Move FlowEngine into modFlow from modWebform #88

**Comment by fyhao** [comment]
start working
